name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Setup JDK 16"
        uses: "actions/setup-java@v2.1.0"
        with:
          distribution: "adopt"
          java-version: "16"
      - name: "Clean Build"
        run: "./gradlew clean build"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Plot target
          # A file, directory or wildcard pattern that describes what to upload
          path: target/
      - name: Upload a Build Artifact 2
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Plot build
          # A file, directory or wildcard pattern that describes what to upload
          path: build/
